# Ignore Travis CI and Appveyor so accurate GPU coverage is reported by GitLab.
codecov:
  ci:
    - !appveyor
    - !travis

coverage:
  ignore:
    - "docs/*.jl"
    - "examples/*.jl"
    - "test/*.jl"
  status:
    patch: false
    project: false
    changes: false

comment: false
