# Ignore Travis CI and Appveyor so accurate GPU coverage is reported by GitLab.
codecov:
  ci:
    - !appveyor
    - !travis

ignore:
  - "docs"
  - "examples"
  - "test"

coverage:
  status:
    patch: false
    project: false
    changes: false

comment: false
