variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'
  JULIA_CUDA_VERBOSE: 'true'

# See: https://github.com/JuliaGPU/gitlab-ci
include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: nvidia/cuda:10.1-cudnn7-devel

julia:1.0:
  extends:
    - .julia:1.0
    - .test
  tags:
    - nvidia

julia:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - nvidia

julia:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia

# julia:1.3:
#   extends:
#     - .julia:1.3
#     - .test
#   tags:
#     - nvidia
# 
# julia:nightly:
#   extends:
#     - .julia:nightly
#     - .test
#   tags:
#     - nvidia
#   allow_failure: true


# other tasks
coverage:
  extends:
    - .julia:1.2
    - .coverage
