variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'

# See: https://github.com/JuliaGPU/gitlab-ci
include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

test:v1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest

test:v1.3:
  extends:
    - .julia:1.3
    - .test
    - .coverage
  tags:
    - nvidia
  image: nvidia/cuda:latest

test:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest
  allow_failure: true
